apiVersion: 1

contactPoints:
  - orgId: 1
    name: slack-webengine
    receivers:
      - uid: slack-webengine
        type: slack
        disableResolveMessage: false
        settings:
          recipient: $SLACK_CHANNEL
          url: $SLACK_WEBHOOK_URL
          title: |
            {{ template "slack.default.title" . }}
          text: |
            {{ template "slack.default.text" . }}
