global:
  scrape_interval: 15s # Default scrape interval

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'django-app'
    static_configs:
      - targets: ['web.railway.internal']
    metrics_path: '/metrics'
    scheme: 'https'
    scrape_interval: 15s
    
