global:
  scrape_interval: 15s # Default scrape interval

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'django-app'
    static_configs:
      - targets: ['llau-systems.up.railway.app']
    metrics_path: '/metrics'
    scheme: 'https'
    scrape_interval: 15s
    honor_labels: true
    relabel_configs:
      - source_labels: [__address__]
        target_label: site
        replacement: 'llau-systems'
    
